import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { ContainerLayout } from "@/components/ContainerLayout";
import ReactQueryProvider from "@/app/context/provider/ReactQueryProvider";
import { CardItemsProvider } from "./context/CardItemsContext";

export const metadata: Metadata = {
  title: "Stor Project",
  description: "Generated by Stor Project",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CardItemsProvider>
          <ReactQueryProvider>
            <Navbar />
            <ContainerLayout>{children}</ContainerLayout>
          </ReactQueryProvider>
        </CardItemsProvider>
      </body>
    </html>
  );
}
